package:
  name: meirlop
  version: "0.0.14"

source:
  path: ..

build:
  entry_points:
    - meirlop = meirlop.__main__:main
    - modiplot = meirlop.motif_distribution_plotting:main

requirements:
  build:
    - python
    - setuptools
    - numpy>=1.18
  run:
    - python>=3.6
    - biopython
    - pybedtools
    - logomaker>=0.8
    - matplotlib>=3.2
    - joblib
    - moods
    - numpy>=1.18
    - pandas
    - scikit-learn
    - statsmodels
    - tqdm
    - python-slugify

test:
  imports:
    - meirlop

about:
  home: https://github.com/npdeloss/meirlop
  license: MIT
  license_file: ../LICENSE
