package:
  name: meirlop
  version: "0.1.1"

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
  run:
    - python
    - biopython >=1.72
    - joblib >=0.12
    - moods >=1.9
    - numpy x.x
    - pandas >=0.23
    - pybedtools >=0.7
    - scikit-learn >=0.19
    - statsmodels >=0.9
    - tqdm >=4.28

test:
  imports:
    - meirlop

about:
  home: https://github.com/npdeloss/meirlop
  license: MIT
  license_file: ../LICENSE
