package:
  name: meirlop
  version: "0.0.12"

source:
  path: ..

build:
  entry_points:
    - meirlop = meirlop.__main__:main
    - modiplot = meirlop.motif_distribution_plotting:main

requirements:
  build:
    - python>=3.6
    - setuptools
    - numpy>=1.13
  run:
    - python>=3.6
    - biopython
    - pybedtools
    - weblogo=3.6
    - joblib
    - moods
    - numpy>=1.13
    - pandas
    - scikit-learn
    - statsmodels
    - tqdm
    - python-slugify

test:
  imports:
    - meirlop

about:
  home: https://github.com/npdeloss/meirlop
  license: MIT
  license_file: ../LICENSE
