package:
  name: meirlop
  version: "0.0.5"

source:
  path: ..

build:
  entry_points:
    - meirlop = meirlop.__main__:main

requirements:
  build:
    - python=3.6
    - setuptools
    - numpy>=1.13
  run:
    - python=3.6
    - biopython
    - pybedtools
    - weblogo
    - joblib
    - moods
    - numpy>=1.13
    - pandas
    - scikit-learn
    - statsmodels
    - tqdm

test:
  imports:
    - meirlop

about:
  home: https://github.com/npdeloss/meirlop
  license: MIT
  license_file: ../LICENSE
